task_name: binary_iscx_mta_mfcp
num_classes: 2
train_split: 0.7
val_split: 0.1
test_split: 0.2
image_size: 112
fixed_bytes: 784
image_model: mobilevit_s
text_model: distilbert-base-uncased
tokenizer_model: distilbert-base-uncased
manifest: dataset/binary/test.csv
subset: test
train:
  subset: train
  dataset: iscx_mta_mfcp
  batch_size: 64
  source_root: dataset/binary/train.csv
val:
  subset: val
  dataset: iscx_mta_mfcp
  batch_size: 64
  source_root: dataset/binary/val.csv
test:
  subset: test
  dataset: iscx_mta_mfcp
  batch_size: 64
  source_root: dataset/binary/test.csv
