task_name: mfcp_6cls
num_classes: 6
train_split: 0.7
val_split: 0.1
test_split: 0.2
image_size: 112
fixed_bytes: 784
image_model: mobilevit_s
text_model: distilbert-base-uncased
tokenizer_model: distilbert-base-uncased
manifest: dataset/mfcp/test.csv
subset: test
train:
  subset: train
  dataset: mfcp
  batch_size: 40
  source_root: dataset/mfcp/train.csv
val:
  subset: val
  dataset: mfcp
  batch_size: 40
  source_root: dataset/mfcp/val.csv
test:
  subset: test
  dataset: mfcp
  batch_size: 40
  source_root: dataset/mfcp/test.csv
