task_name: mfcp_6cls
num_classes: 6
train_split: 0.7
val_split: 0.1
test_split: 0.2
image_size: 112
fixed_bytes: 784
train:
  subset: train
  dataset: mfcp
  batch_size: 40
  source_root: SourceData/mfcp
val:
  subset: val
  dataset: mfcp
  batch_size: 40
  source_root: SourceData/mfcp
test:
  subset: test
  dataset: mfcp
  batch_size: 40
  source_root: SourceData/mfcp
