task_name: mta_7cls
num_classes: 7
train_split: 0.7
val_split: 0.1
test_split: 0.2
image_size: 112
fixed_bytes: 784
image_model: mobilevit_s
text_model: distilbert-base-uncased
tokenizer_model: distilbert-base-uncased
manifest: dataset/mta/test.csv
subset: test
train:
  subset: train
  dataset: mta_multiclass
  batch_size: 48
  source_root: dataset/mta/train.csv
val:
  subset: val
  dataset: mta_multiclass
  batch_size: 48
  source_root: dataset/mta/val.csv
test:
  subset: test
  dataset: mta_multiclass
  batch_size: 48
  source_root: dataset/mta/test.csv
